ServerRoot "/etc/httpd"
PidFile /app/applications/war/bmon-ai-agent/bmon-ops-frontend/httpd.pid
Listen 19090

LoadModule authz_host_module modules/mod_authz_host.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule dir_module modules/mod_dir.so
LoadModule rewrite_module modules/mod_rewrite.so

TypesConfig /etc/mime.types
DirectoryIndex index.html

ErrorLog /dev/null
CustomLog /dev/null combined

DocumentRoot "/app/applications/war/bmon-ai-agent/bmon-ops-frontend/html"

<Directory "/app/applications/war/bmon-ai-agent/bmon-ops-frontend/html">
    Options -Indexes +FollowSymLinks
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>

RewriteEngine On
RewriteBase /
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
